version: '3'

services:
  termometro:
    build: ./Termometro
    ports:
    - "8080:8080"
    command: node server.js

  motorr:
    build: ./Motor
    ports:
    - "8081:8081"
    command: node server.js

  led:
    build: ./Led
    ports:
    - "8082:8082"
    command: node server.js  
    




